version: '2'

services:
  app:
    image: 'portal-transaccional:latest'
    build:
      context: .
    container_name: app-portal-transaccional
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/portal-transaccional
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db-portal-transaccional
    ports:
      - "5432:5432"
    volumes:
      - ../../../sql/BaseDatos.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres